// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaUNBNDbp541213QTGq6lRE-uiV79mMeo',
    appId: '1:353289210760:web:01b4eab26b5455f956c83d',
    messagingSenderId: '353289210760',
    projectId: 'chatapp-6fb24',
    authDomain: 'chatapp-6fb24.firebaseapp.com',
    storageBucket: 'chatapp-6fb24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRPj5GhNdgR_ECj9UUAA-V48ew7u5JsQ',
    appId: '1:353289210760:android:f5a390a6610eada856c83d',
    messagingSenderId: '353289210760',
    projectId: 'chatapp-6fb24',
    storageBucket: 'chatapp-6fb24.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaUNBNDbp541213QTGq6lRE-uiV79mMeo',
    appId: '1:353289210760:web:edd92ed159261c4156c83d',
    messagingSenderId: '353289210760',
    projectId: 'chatapp-6fb24',
    authDomain: 'chatapp-6fb24.firebaseapp.com',
    storageBucket: 'chatapp-6fb24.firebasestorage.app',
  );
}
