// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOAxguAhgGvVutzBmAiyu-NJQx_WPHSqs',
    appId: '1:906123916363:web:dee05bf3b7c37e217249ce',
    messagingSenderId: '906123916363',
    projectId: 'userauth-a21d3',
    authDomain: 'userauth-a21d3.firebaseapp.com',
    storageBucket: 'userauth-a21d3.appspot.com',
    measurementId: 'G-LCRPEVS15G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2168MUhnKOIsOVUbe5kKJ3-YT46z40jU',
    appId: '1:906123916363:android:12eaaeeffce747557249ce',
    messagingSenderId: '906123916363',
    projectId: 'userauth-a21d3',
    storageBucket: 'userauth-a21d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8p2ogv4I3qMwTS-pQPpZz1FVtzayGonQ',
    appId: '1:906123916363:ios:4bd372c20d90d7f67249ce',
    messagingSenderId: '906123916363',
    projectId: 'userauth-a21d3',
    storageBucket: 'userauth-a21d3.appspot.com',
    iosBundleId: 'com.example.userauthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8p2ogv4I3qMwTS-pQPpZz1FVtzayGonQ',
    appId: '1:906123916363:ios:4bd372c20d90d7f67249ce',
    messagingSenderId: '906123916363',
    projectId: 'userauth-a21d3',
    storageBucket: 'userauth-a21d3.appspot.com',
    iosBundleId: 'com.example.userauthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOAxguAhgGvVutzBmAiyu-NJQx_WPHSqs',
    appId: '1:906123916363:web:dfd8fb7895cd77267249ce',
    messagingSenderId: '906123916363',
    projectId: 'userauth-a21d3',
    authDomain: 'userauth-a21d3.firebaseapp.com',
    storageBucket: 'userauth-a21d3.appspot.com',
    measurementId: 'G-TLF01CXGZX',
  );
}
