// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxOSCZNk87a9Hgr3vfwiWJwF7ZslkANdo',
    appId: '1:327612343885:web:5144ded945429f0eaa1e04',
    messagingSenderId: '327612343885',
    projectId: 'fir-todo-b7a5c',
    authDomain: 'fir-todo-b7a5c.firebaseapp.com',
    storageBucket: 'fir-todo-b7a5c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlZippok0GjhIcCfWV9GSihEzagsw040',
    appId: '1:327612343885:android:e594d2e66f336d1daa1e04',
    messagingSenderId: '327612343885',
    projectId: 'fir-todo-b7a5c',
    storageBucket: 'fir-todo-b7a5c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxOSCZNk87a9Hgr3vfwiWJwF7ZslkANdo',
    appId: '1:327612343885:web:2fbb09a3412849d8aa1e04',
    messagingSenderId: '327612343885',
    projectId: 'fir-todo-b7a5c',
    authDomain: 'fir-todo-b7a5c.firebaseapp.com',
    storageBucket: 'fir-todo-b7a5c.firebasestorage.app',
  );
}
